// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr-wdUGbWq8rBWgGQxyMcMW6ukcSB_wZc',
    appId: '1:147183466756:web:38f2017cb52391d59cb851',
    messagingSenderId: '147183466756',
    projectId: 'tobee-e628a',
    authDomain: 'tobee-e628a.firebaseapp.com',
    storageBucket: 'tobee-e628a.firebasestorage.app',
    measurementId: 'G-WM3BLVKXVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6_tY4m2qw5eDqIcdoifd0bCgia_D8Hiw',
    appId: '1:147183466756:android:598b7a9c6fce88d39cb851',
    messagingSenderId: '147183466756',
    projectId: 'tobee-e628a',
    storageBucket: 'tobee-e628a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUq5rQTPcZdgLteZYCDFcVBhedFItjclk',
    appId: '1:147183466756:ios:4c8f470c629ff0dd9cb851',
    messagingSenderId: '147183466756',
    projectId: 'tobee-e628a',
    storageBucket: 'tobee-e628a.firebasestorage.app',
    iosBundleId: 'com.example.toBee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUq5rQTPcZdgLteZYCDFcVBhedFItjclk',
    appId: '1:147183466756:ios:4c8f470c629ff0dd9cb851',
    messagingSenderId: '147183466756',
    projectId: 'tobee-e628a',
    storageBucket: 'tobee-e628a.firebasestorage.app',
    iosBundleId: 'com.example.toBee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr-wdUGbWq8rBWgGQxyMcMW6ukcSB_wZc',
    appId: '1:147183466756:web:943ab996c421232e9cb851',
    messagingSenderId: '147183466756',
    projectId: 'tobee-e628a',
    authDomain: 'tobee-e628a.firebaseapp.com',
    storageBucket: 'tobee-e628a.firebasestorage.app',
    measurementId: 'G-K51MQR420Z',
  );
}
